"use client";
import {useEffect,useMemo,useState} from "react";
import Shell from "@/components/Shell";
import {supabaseBrowser} from "@/lib/supabase";
type Q={id:string;number:string;title:string;status:string;total:number;valid_until?:string;clients?:{name?:string}|null};
const labels:any={draft:"Brouillon",sent:"Envoyé",accepted:"Accepté",rejected:"Refusé",expired:"Expiré"};
export default function Page(){const sb=useMemo(()=>supabaseBrowser(),[]);const [quotes,setQuotes]=useState<Q[]>([]),[clients,setClients]=useState<any[]>([]),[open,setOpen]=useState(false),[msg,setMsg]=useState(""),[f,setF]=useState<any>({client_id:"",title:"",total:"",valid_until:""});
async function load(){if(!sb)return;const [a,b]=await Promise.all([sb.from("quotes").select("id,number,title,status,total,valid_until,clients(name)").order("created_at",{ascending:false}),sb.from("clients").select("id,name").order("name")]);if(!a.error)setQuotes((a.data||[]) as any);if(!b.error)setClients(b.data||[])}
useEffect(()=>{load()},[]);
async function save(e:React.FormEvent){e.preventDefault();if(!sb)return;setMsg("");const number="DEV-"+new Date().toISOString().slice(0,10).replaceAll("-","")+"-"+String(Date.now()).slice(-4);const total=Number(f.total||0);const {error}=await sb.from("quotes").insert({client_id:f.client_id,number,title:f.title,status:"draft",subtotal:total,tax_amount:0,total,valid_until:f.valid_until||null});if(error){setMsg(error.message);return}setOpen(false);setF({client_id:"",title:"",total:"",valid_until:""});load()}
async function status(id:string,status:string){if(!sb)return;await sb.from("quotes").update({status}).eq("id",id);load()}
const accepted=quotes.filter(x=>x.status==="accepted").reduce((s,x)=>s+Number(x.total||0),0),pipeline=quotes.filter(x=>["draft","sent"].includes(x.status)).reduce((s,x)=>s+Number(x.total||0),0);
return <Shell title="Commercial"><section className="crmHero"><div><span className="dashBadge">PERFORMANCE COMMERCIALE</span><h2>Devis & ventes</h2><p>Créez les devis, suivez les montants en négociation et les ventes conclues.</p></div><button className="btn goldBtn" onClick={()=>setOpen(true)}>+ Nouveau devis</button></section>
<section className="crmStats"><article><span>Devis</span><strong>{quotes.length}</strong></article><article><span>Pipeline devis</span><strong>{pipeline.toLocaleString("fr-FR")} FCFA</strong></article><article><span>Acceptés</span><strong>{quotes.filter(x=>x.status==="accepted").length}</strong></article><article><span>Ventes conclues</span><strong>{accepted.toLocaleString("fr-FR")} FCFA</strong></article></section>
<section className="crmEmpty" style={{textAlign:"left"}}><b>Devis récents</b>{quotes.length?quotes.map(q=><article className="prospectCard" key={q.id} style={{marginTop:12}}><strong>{q.number} · {q.title}</strong><small>{q.clients?.name||"Client"} · {Number(q.total).toLocaleString("fr-FR")} FCFA</small><select value={q.status} onChange={e=>status(q.id,e.target.value)}>{Object.entries(labels).map(([v,n])=><option value={v} key={v}>{String(n)}</option>)}</select></article>):<p>Aucun devis enregistré.</p>}</section>
{open&&<div className="modal"><form className="modalCard premiumModal" onSubmit={save}><div className="modalTop"><div><span className="dashBadge">NOUVEAU DEVIS</span><h2>Créer un devis</h2></div><button type="button" onClick={()=>setOpen(false)}>×</button></div><label>Client<select required value={f.client_id} onChange={e=>setF({...f,client_id:e.target.value})}><option value="">Sélectionner</option>{clients.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label><label>Objet du devis<input required value={f.title} onChange={e=>setF({...f,title:e.target.value})}/></label><div className="form2"><label>Montant FCFA<input required type="number" min="0" value={f.total} onChange={e=>setF({...f,total:e.target.value})}/></label><label>Valide jusqu’au<input type="date" value={f.valid_until} onChange={e=>setF({...f,valid_until:e.target.value})}/></label></div>{msg&&<p className="error">{msg}</p>}<button className="btn goldBtn full">Enregistrer le devis</button></form></div>}</Shell>}