"use client";
import {useEffect,useMemo,useState} from "react";
import Shell from "@/components/Shell";
import {supabaseBrowser} from "@/lib/supabase";
type Product={id:string;title:string;description?:string;product_type:string;price:number;active:boolean;created_at:string};
type Order={id:string;order_number:string;buyer_name:string;amount:number;status:string;created_at:string;training_products?:{title?:string}|null};
export default function Academy(){
 const sb=useMemo(()=>supabaseBrowser(),[]),[products,setProducts]=useState<Product[]>([]),[orders,setOrders]=useState<Order[]>([]),[open,setOpen]=useState(false),[msg,setMsg]=useState(""),[f,setF]=useState({title:"",description:"",product_type:"video",price:"",active:true});
 async function load(){if(!sb)return;const[a,b]=await Promise.all([sb.from("training_products").select("id,title,description,product_type,price,active,created_at").order("created_at",{ascending:false}),sb.from("training_orders").select("id,order_number,buyer_name,amount,status,created_at,training_products(title)").order("created_at",{ascending:false}).limit(20)]);if(!a.error)setProducts((a.data??[]) as Product[]);if(!b.error)setOrders((b.data??[]) as any)}
 useEffect(()=>{load()},[]);
 async function save(e:React.FormEvent){e.preventDefault();if(!sb)return;setMsg("");const slug=f.title.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")+"-"+String(Date.now()).slice(-4);const{error}=await sb.from("training_products").insert({title:f.title.trim(),description:f.description||null,product_type:f.product_type,price:Number(f.price||0),active:f.active,slug});if(error){setMsg("Création impossible : "+error.message);return}setOpen(false);setF({title:"",description:"",product_type:"video",price:"",active:true});setMsg("Formation créée.");load()}
 async function toggle(p:Product){if(!sb)return;await sb.from("training_products").update({active:!p.active}).eq("id",p.id);load()}
 const active=products.filter(x=>x.active).length,paid=orders.filter(x=>x.status==="paid"),ca=paid.reduce((s,x)=>s+Number(x.amount||0),0);
 return <Shell title="KARMEO Academy">
  <section className="crmHero"><div><span className="dashBadge">FORMATION & CONTENU</span><h2>KARMEO Academy</h2><p>Créez vos formations, commercialisez vos contenus et contrôlez les accès clients.</p></div><button className="btn goldBtn" onClick={()=>setOpen(true)}>+ Nouvelle formation</button></section>
  {msg&&<p className="notice">{msg}</p>}
  <section className="crmStats"><article><span>Formations</span><strong>{products.length}</strong></article><article><span>Actives</span><strong>{active}</strong></article><article><span>Commandes payées</span><strong>{paid.length}</strong></article><article><span>CA Academy</span><strong>{ca.toLocaleString("fr-FR")} FCFA</strong></article></section>
  <section className="panel"><div className="panelHead"><div><span className="dashBadge">CATALOGUE</span><h3>Formations & produits digitaux</h3></div></div><div className="cards">{products.length?products.map(p=><article className="card" key={p.id}><span className="dashBadge">{p.product_type.toUpperCase()}</span><h3>{p.title}</h3><p>{p.description||"Aucune description."}</p><strong>{Number(p.price).toLocaleString("fr-FR")} FCFA</strong><div className="row"><span>{p.active?"Disponible":"Désactivée"}</span><button className="miniBtn" onClick={()=>toggle(p)}>{p.active?"Désactiver":"Activer"}</button></div></article>):<div className="card"><b>Aucune formation</b><p>Créez le premier produit KARMEO Academy.</p></div>}</div></section>
  <section className="panel"><div className="panelHead"><div><span className="dashBadge">VENTES</span><h3>Commandes récentes</h3></div></div><div className="cards">{orders.length?orders.map(o=><article className="card" key={o.id}><b>{o.order_number}</b><p>{o.buyer_name} · {o.training_products?.title||"Formation"}</p><strong>{Number(o.amount).toLocaleString("fr-FR")} FCFA</strong><small>Statut : {o.status}</small></article>):<div className="card"><b>Aucune commande</b><p>Les ventes Academy apparaîtront ici.</p></div>}</div></section>
  {open&&<div className="modal"><form className="modalCard premiumModal" onSubmit={save}><div className="modalTop"><div><span className="dashBadge">ACADEMY</span><h2>Nouvelle formation</h2></div><button type="button" onClick={()=>setOpen(false)}>×</button></div><label>Titre<input required value={f.title} onChange={e=>setF({...f,title:e.target.value})}/></label><label>Description<textarea value={f.description} onChange={e=>setF({...f,description:e.target.value})}/></label><div className="form2"><label>Format<select value={f.product_type} onChange={e=>setF({...f,product_type:e.target.value})}><option value="video">Formation vidéo</option><option value="pdf">Document / PDF</option><option value="bundle">Pack vidéo + documents</option></select></label><label>Prix FCFA<input required type="number" min="0" value={f.price} onChange={e=>setF({...f,price:e.target.value})}/></label></div><button className="btn goldBtn full">Créer la formation</button></form></div>}
 </Shell>
}