"use client";
import { useEffect,useMemo,useState } from "react";
import {useRouter} from "next/navigation";
import Shell from "@/components/Shell";
import { supabaseBrowser } from "@/lib/supabase";
type Lead={id:string;name:string;phone?:string;source?:string;status:string;need?:string;budget?:number;client_id?:string};
const stages=[["Nouveau","new"],["Contacté","contacted"],["Qualifié","qualified"],["Rendez-vous","appointment"],["Étude","study"],["Devis","quote_sent"],["Négociation","negotiation"],["Gagné","won"],["Perdu","lost"]] as const;
const empty={name:"",phone:"",source:"WhatsApp",status:"new",need:"",budget:""};
export default function Page(){
 const [leads,setLeads]=useState<Lead[]>([]),[q,setQ]=useState(""),[open,setOpen]=useState(false),[form,setForm]=useState<any>(empty),[msg,setMsg]=useState(""),[campaigns,setCampaigns]=useState<any[]>([]),[campaignOpen,setCampaignOpen]=useState(false),[campaign,setCampaign]=useState<any>({name:"",channel:"Facebook",offer:""});
 const sb=useMemo(()=>supabaseBrowser(),[]);const router=useRouter();
 async function load(){if(!sb)return;const {data,error}=await sb.from("leads").select("id,name,phone,source,status,need,budget,client_id").order("created_at",{ascending:false});if(!error)setLeads((data||[]) as Lead[]);const r=await sb.from("marketing_campaigns").select("*").order("created_at",{ascending:false});if(!r.error)setCampaigns(r.data||[])}
 useEffect(()=>{load()},[]);
 async function save(e:React.FormEvent){e.preventDefault();if(!sb)return;setMsg("");const {error}=await sb.from("leads").insert({name:form.name.trim(),phone:form.phone||null,source:form.source,need:form.need||null,budget:form.budget?Number(form.budget):0,status:form.status});if(error){setMsg("Enregistrement impossible : "+error.message);return}setOpen(false);setForm(empty);await load()}
 async function addCampaign(e:React.FormEvent){e.preventDefault();if(!sb)return;const slug=(campaign.name+"-"+campaign.channel).toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")+"-"+String(Date.now()).slice(-4);const{error}=await sb.from("marketing_campaigns").insert({...campaign,slug});if(error){setMsg(error.message);return}setCampaignOpen(false);setCampaign({name:"",channel:"Facebook",offer:""});load()}
 function campaignUrl(x:any){return `${window.location.origin}/demande?source=${encodeURIComponent(x.channel+" · "+x.name)}`}
 async function copyCampaign(x:any){await navigator.clipboard.writeText(campaignUrl(x));setMsg("Lien copié : "+x.name)}
 async function convert(id:string){if(!sb)return;setMsg("");const{data,error}=await sb.rpc("convert_lead_to_client",{p_lead_id:id});if(error){setMsg("Conversion impossible : "+error.message);return}setMsg("Prospect converti en client.");await load()}
 async function move(id:string,status:string){if(!sb)return;const lead=leads.find(x=>x.id===id);if(!lead)return;if(status==="quote_sent"){setMsg("");let clientId=lead.client_id;if(!clientId){const r=await sb.rpc("convert_lead_to_client",{p_lead_id:id});if(r.error||!r.data){setMsg("Conversion client impossible : "+(r.error?.message||"Erreur"));return}clientId=String(r.data)}await sb.from("leads").update({status:"quote_sent"}).eq("id",id);router.push("/commercial?client="+encodeURIComponent(clientId)+"&lead="+encodeURIComponent(id));return}const before=leads;setLeads(x=>x.map(l=>l.id===id?{...l,status}:l));const {error}=await sb.from("leads").update({status}).eq("id",id);if(error){setLeads(before);setMsg("Mise à jour impossible : "+error.message)}}
 const filtered=leads.filter(l=>[l.name,l.phone,l.need].join(" ").toLowerCase().includes(q.toLowerCase()));
 return <Shell title="CRM">
 <section className="crmHero"><div><span className="dashBadge">PIPELINE COMMERCIAL</span><h2>Prospects & opportunités</h2><p>Centralisez les demandes, qualifiez les prospects et pilotez chaque vente jusqu’au closing.</p></div><div style={{display:"flex",gap:8,flexWrap:"wrap"}}><button className="btn" onClick={()=>setCampaignOpen(true)}>+ Lien campagne</button><button className="btn goldBtn" onClick={()=>setOpen(true)}>+ Nouveau prospect</button></div></section>
 <section className="crmStats"><article><span>Prospects</span><strong>{leads.length}</strong></article><article><span>Qualifiés</span><strong>{leads.filter(x=>x.status==="qualified").length}</strong></article><article><span>Devis / négociation</span><strong>{leads.filter(x=>["quote_sent","negotiation"].includes(x.status)).length}</strong></article><article><span>Gagnés</span><strong>{leads.filter(x=>x.status==="won").length}</strong></article></section>
 <section className="crmEmpty" style={{textAlign:"left",marginBottom:16}}><div style={{display:"flex",justifyContent:"space-between",gap:10,alignItems:"center"}}><div><span className="dashBadge">ACQUISITION</span><h3>Liens campagnes</h3></div><button className="miniBtn" onClick={()=>setCampaignOpen(true)}>+ Créer</button></div>{campaigns.slice(0,5).map(x=><article className="prospectCard" key={x.id} style={{marginTop:8}}><strong>{x.name}</strong><small>{x.channel}{x.offer?" · "+x.offer:""}</small><button className="miniBtn" onClick={()=>copyCampaign(x)}>Copier le lien prospect</button></article>)}</section><div className="crmToolbar"><input placeholder="Rechercher un prospect, téléphone, besoin…" value={q} onChange={e=>setQ(e.target.value)}/><button className="btn goldBtn" onClick={()=>setOpen(true)}>+ Ajouter</button></div>
 {msg&&<p className="error">{msg}</p>}
 <section className="crmPipeline">{stages.slice(0,8).map(([label,key])=><div className="crmColumn" key={key}><div className="crmColumnHead"><b>{label}</b><span>{filtered.filter(x=>x.status===key).length}</span></div>{filtered.filter(x=>x.status===key).map(l=><article className="prospectCard" key={l.id}><strong>{l.name}</strong><small>{l.need||"Besoin à qualifier"}</small>{l.phone&&<a href={"tel:"+l.phone}>{l.phone}</a>}<div className="prospectMeta"><span>{l.source||"Direct"}</span>{l.budget?<b>{Number(l.budget).toLocaleString("fr-FR")} FCFA</b>:null}</div><select value={l.status} onChange={e=>move(l.id,e.target.value)}>{stages.map(([n,v])=><option value={v} key={v}>{n}</option>)}</select>{l.client_id?<a className="miniBtn" href="/clients">Client créé ✓</a>:<button className="miniBtn" onClick={()=>convert(l.id)}>Convertir en client</button>}</article>)}</div>)}</section>
 {!leads.length&&<div className="crmEmpty"><b>Aucun prospect enregistré</b><p>Ajoutez votre premier prospect pour démarrer le pipeline commercial KARMEO.</p><button className="btn goldBtn" onClick={()=>setOpen(true)}>Créer un prospect</button></div>}
 {campaignOpen&&<div className="modal"><form className="modalCard premiumModal" onSubmit={addCampaign}><div className="modalTop"><div><span className="dashBadge">ACQUISITION</span><h2>Créer un lien campagne</h2></div><button type="button" onClick={()=>setCampaignOpen(false)}>×</button></div><label>Nom de la campagne<input required placeholder="Ex. Pergola Octobre" value={campaign.name} onChange={e=>setCampaign({...campaign,name:e.target.value})}/></label><label>Réseau / canal<select value={campaign.channel} onChange={e=>setCampaign({...campaign,channel:e.target.value})}><option>Facebook</option><option>Instagram</option><option>TikTok</option><option>WhatsApp</option><option>Google</option><option>Autre</option></select></label><label>Offre / activité<input placeholder="Ex. Pergola premium" value={campaign.offer} onChange={e=>setCampaign({...campaign,offer:e.target.value})}/></label><button className="btn goldBtn full">Créer le lien</button></form></div>}{open&&<div className="modal"><form className="modalCard premiumModal" onSubmit={save}><div className="modalTop"><div><span className="dashBadge">NOUVEAU LEAD</span><h2>Ajouter un prospect</h2></div><button type="button" onClick={()=>setOpen(false)}>×</button></div>
 <label>Nom / entreprise<input required minLength={2} value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label>
 <label>Téléphone<input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label>
 <div className="form2"><label>Source<select value={form.source} onChange={e=>setForm({...form,source:e.target.value})}><option>WhatsApp</option><option>Facebook</option><option>Instagram</option><option>TikTok</option><option>Recommandation</option><option>Direct</option></select></label><label>Budget FCFA<input type="number" min="0" value={form.budget} onChange={e=>setForm({...form,budget:e.target.value})}/></label></div>
 <label>Besoin<textarea placeholder="Pergola, construction, terrain, rénovation…" value={form.need} onChange={e=>setForm({...form,need:e.target.value})}/></label>
 <button className="btn goldBtn full">Enregistrer le prospect</button></form></div>}
 </Shell>
}