"use client";
import Link from "next/link";
import {useEffect,useMemo,useState} from "react";
import Shell from "@/components/Shell";
import {supabaseBrowser} from "@/lib/supabase";
const modules=[
 ["CRM","Prospects, relances et pipeline","/crm","◎",["direction","admin","marketing","commercial"]],
 ["Commercial","Devis, ventes et objectifs","/commercial","↗",["direction","admin","commercial"]],
 ["Clients","Base clients et historique","/clients","♙",["direction","admin","commercial","finance","project_manager"]],
 ["Chantiers","Suivi des projets et travaux","/chantiers","⌂",["direction","admin","project_manager"]],
 ["Finance","Encaissements et trésorerie","/finance","₣",["direction","admin","finance"]],
 ["Achats","Fournisseurs et dépenses","/achats","▣",["direction","admin","project_manager","finance"]],
 ["Documents","Contrats, devis et fichiers","/documents","□",["direction","admin","project_manager","finance"]],
 ["Rapports","KPI et pilotage","/rapports","▥",["direction","admin","finance"]]
] as const;
function directionRole(r:string){return r==="direction"||r==="admin"}\nexport default function Page(){
 const sb=useMemo(()=>supabaseBrowser(),[]),[role,setRole]=useState(""),[k,setK]=useState({ca:0,leads:0,clients:0,projects:0,pipeline:0,paid:0}),[perf,setPerf]=useState<any[]>([]),[siteHealth,setSiteHealth]=useState<any[]>([]);
 useEffect(()=>{(async()=>{if(!sb)return;const{data:{user}}=await sb.auth.getUser();if(!user)return;const pr=await sb.from("profiles").select("role").eq("id",user.id).maybeSingle();const r=pr.data?.role||"";setRole(r);const[a,b,c,d,e,p,h]=await Promise.all([sb.from("quotes").select("total,status"),sb.from("leads").select("id,status"),sb.from("clients").select("id",{count:"exact",head:true}),sb.from("projects").select("id,status"),sb.from("payments").select("amount"),r==="direction"||r==="admin"?sb.from("sales_agent_performance").select("*").order("accepted_revenue",{ascending:false}).limit(5):Promise.resolve({data:[]}) as any,directionRole(r)?sb.from("projects").select("id,reference,name,budget,contract_value,progress,status,end_date,expenses(amount)"):Promise.resolve({data:[]}) as any]);const qs=a.data||[];setK({ca:qs.filter((x:any)=>x.status==="accepted").reduce((s:number,x:any)=>s+Number(x.total||0),0),pipeline:qs.filter((x:any)=>["draft","sent"].includes(x.status)).reduce((s:number,x:any)=>s+Number(x.total||0),0),paid:(e.data||[]).reduce((s:number,x:any)=>s+Number(x.amount||0),0),leads:(b.data||[]).filter((x:any)=>!["won","lost"].includes(x.status)).length,clients:c.count||0,projects:(d.data||[]).filter((x:any)=>!["termine","annule"].includes(x.status)).length});setPerf(p.data||[]);setSiteHealth((h.data||[]).filter((x:any)=>!["termine","annule"].includes(x.status)).map((x:any)=>{const spent=(x.expenses||[]).reduce((s:number,e:any)=>s+Number(e.amount||0),0),budget=Number(x.budget||0),contract=Number(x.contract_value||0),progress=Number(x.progress||0),budgetPct=budget>0?spent/budget*100:0,loss=spent>contract,risk=(budget>0&&spent>budget)||(progress>0&&budgetPct>progress+20),warning=progress>0&&budgetPct>progress+10,late=x.end_date&&new Date(x.end_date)<new Date()&&progress<100;return{...x,spent,budgetPct,health:loss?"PERTE":risk?"RISQUE":warning?"VIGILANCE":"MAÎTRISÉ",level:loss||risk?"red":warning?"orange":"green",late}}))})()},[sb]);
 const visible=modules.filter(([, , , ,roles])=>!role||roles.includes(role as any)),direction=role==="direction"||role==="admin";
 return <Shell title="Tableau de bord"><section className="heroDash"><div><span className="dashBadge">{direction?"CENTRE DE PILOTAGE DIRECTION":"ESPACE DE TRAVAIL"}</span><h2>Bonjour, bienvenue sur KARMEO ERP/CRM</h2><p>{direction?"Vue consolidée de l’activité commerciale, financière et opérationnelle.":"Vos indicateurs et outils selon votre niveau d’accès."}</p></div><div className="heroDate">KARMEO GROUP<br/><small>Abidjan · Côte d’Ivoire</small></div></section>
 <section className="kpiGrid"><article className="kpi"><span>Chiffre d’affaires</span><strong>{k.ca.toLocaleString("fr-FR")} FCFA</strong><small>Ventes acceptées visibles</small></article><article className="kpi"><span>Pipeline</span><strong>{k.pipeline.toLocaleString("fr-FR")} FCFA</strong><small>Devis en cours</small></article><article className="kpi"><span>Prospects actifs</span><strong>{k.leads}</strong><small>Pipeline CRM</small></article><article className="kpi"><span>Clients</span><strong>{k.clients}</strong><small>Base accessible</small></article></section>
 {direction&&siteHealth.length>0&&<section className="panel"><div className="panelHead"><div><span className="dashBadge">ALERTES CHANTIERS</span><h3>Santé opérationnelle & financière</h3></div><Link className="miniBtn" href="/chantiers">Voir les chantiers</Link></div><div className="statsGrid"><div className="statCard"><span>🟢 Maîtrisés</span><strong>{siteHealth.filter(x=>x.level==="green").length}</strong></div><div className="statCard"><span>🟠 Vigilance</span><strong>{siteHealth.filter(x=>x.level==="orange").length}</strong></div><div className="statCard"><span>🔴 Risque / perte</span><strong>{siteHealth.filter(x=>x.level==="red").length}</strong></div></div>{siteHealth.filter(x=>x.level!=="green"||x.late).slice(0,5).map(x=><Link href={"/chantiers/"+x.id} className="card" key={x.id}><b>{x.level==="red"?"🔴":x.level==="orange"?"🟠":"🟢"} {x.reference||"CHANTIER"} · {x.name}</b><p>{x.health}{x.late?" · RETARD":""}</p><small>{x.budgetPct.toFixed(1)}% du budget consommé · {Number(x.progress||0)}% d’avancement</small></Link>)}</section>}\n {direction&&<section className="panel"><div className="panelHead"><div><span className="dashBadge">DIRECTION</span><h3>Vue exécutive</h3></div></div><div className="statsGrid"><div className="statCard"><span>Encaissements</span><strong>{k.paid.toLocaleString("fr-FR")} FCFA</strong><small>Paiements enregistrés</small></div><div className="statCard"><span>Chantiers actifs</span><strong>{k.projects}</strong><small>Opérations en cours</small></div><div className="statCard"><span>Commerciaux suivis</span><strong>{perf.length}</strong><small>Performance consolidée</small></div></div>{perf.length>0&&<div className="cards">{perf.map((p:any)=><article className="card" key={p.id}><b>{p.display_name}</b><p>CA accepté : <strong>{Number(p.accepted_revenue).toLocaleString("fr-FR")} FCFA</strong></p><small>{Number(p.quotes_count)} devis · {Number(p.accepted_count)} accepté(s)</small></article>)}</div>}</section>}
 <div className="dashHeading"><div><h3>Modules de gestion</h3><p>Accès rapide aux fonctions autorisées.</p></div><span>V1 · Production</span></div><section className="moduleGrid">{visible.map(([name,desc,href,icon])=><Link className="moduleCard" href={href} key={href}><div className="moduleIcon">{icon}</div><div><strong>{name}</strong><p>{desc}</p></div><b>›</b></Link>)}</section>
 </Shell>
}