"use client";
import Link from "next/link";
import {useEffect,useMemo,useState} from "react";
import Shell from "@/components/Shell";
import {supabaseBrowser} from "@/lib/supabase";
const modules=[["CRM","Prospects, relances et pipeline","/crm","◎"],["Commercial","Devis, ventes et objectifs","/commercial","↗"],["Clients","Base clients et historique","/clients","♙"],["Chantiers","Suivi des projets et travaux","/chantiers","⌂"],["Finance","Encaissements et trésorerie","/finance","₣"],["Achats","Fournisseurs et dépenses","/achats","▣"],["Documents","Contrats, devis et fichiers","/documents","□"],["Rapports","KPI et pilotage","/rapports","▥"]];
export default function Page(){const sb=useMemo(()=>supabaseBrowser(),[]);const[k,setK]=useState({ca:0,leads:0,clients:0,projects:0});useEffect(()=>{(async()=>{if(!sb)return;const[a,b,c,d]=await Promise.all([sb.from("quotes").select("total").eq("status","accepted"),sb.from("leads").select("id,status"),sb.from("clients").select("id",{count:"exact",head:true}),sb.from("projects").select("id,status")]);setK({ca:(a.data||[]).reduce((s:any,x:any)=>s+Number(x.total||0),0),leads:(b.data||[]).filter((x:any)=>!["won","lost"].includes(x.status)).length,clients:c.count||0,projects:(d.data||[]).filter((x:any)=>!["termine","annule"].includes(x.status)).length})})()},[sb]);
return <Shell title="Tableau de bord"><section className="heroDash"><div><span className="dashBadge">CENTRE DE PILOTAGE</span><h2>Bonjour, bienvenue sur KARMEO ERP/CRM</h2><p>Vue consolidée de votre activité commerciale, financière et opérationnelle.</p></div><div className="heroDate">KARMEO GROUP<br/><small>Abidjan · Côte d’Ivoire</small></div></section>
<section className="kpiGrid"><article className="kpi"><span>Chiffre d’affaires</span><strong>{k.ca.toLocaleString("fr-FR")} FCFA</strong><small>Ventes acceptées</small></article><article className="kpi"><span>Prospects actifs</span><strong>{k.leads}</strong><small>Pipeline CRM</small></article><article className="kpi"><span>Clients</span><strong>{k.clients}</strong><small>Base clients</small></article><article className="kpi"><span>Chantiers actifs</span><strong>{k.projects}</strong><small>Suivi opérationnel</small></article></section>
<div className="dashHeading"><div><h3>Modules de gestion</h3><p>Accès rapide aux fonctions de KARMEO.</p></div><span>V1 · Production</span></div><section className="moduleGrid">{modules.map(([name,desc,href,icon])=><Link className="moduleCard" href={href} key={href}><div className="moduleIcon">{icon}</div><div><strong>{name}</strong><p>{desc}</p></div><b>›</b></Link>)}</section>
<section className="dashBottom"><article><span className="dashBadge">ACTIVITÉ</span><h3>Données synchronisées</h3><p>Les KPI sont maintenant calculés depuis Supabase et évoluent avec l’activité enregistrée dans KARMEO.</p></article><article><span className="dashBadge">DIRECTION</span><h3>Pilotage centralisé</h3><p>CRM, clients, ventes, chantiers, dépenses et reporting sont réunis dans la même plateforme.</p></article></section></Shell>}