"use client";
import{useEffect,useMemo,useState}from"react";import{useParams}from"next/navigation";import Link from"next/link";import Shell from"@/components/Shell";import{supabaseBrowser}from"@/lib/supabase";
export default function Page(){const{id}=useParams<{id:string}>(),sb=useMemo(()=>supabaseBrowser(),[]),[p,setP]=useState<any>(null),[tasks,setTasks]=useState<any[]>([]),[logs,setLogs]=useState<any[]>([]),[task,setTask]=useState(""),[note,setNote]=useState(""),[msg,setMsg]=useState(""),[expenses,setExpenses]=useState<any[]>([]),[expense,setExpense]=useState<any>({category:"Matériaux",amount:"",supplier:""});
async function load(){if(!sb||!id)return;const[a,b,c,d]=await Promise.all([sb.from("projects").select("*,clients(name)").eq("id",id).single(),sb.from("project_tasks").select("*").eq("project_id",id).order("created_at"),sb.from("project_logs").select("*").eq("project_id",id).order("log_date",{ascending:false}).limit(20),sb.from("expenses").select("*").eq("project_id",id).order("spent_at",{ascending:false})]);if(a.error){setMsg(a.error.message);return}setP(a.data);setTasks(b.data||[]);setLogs(c.data||[]);setExpenses(d.data||[])}useEffect(()=>{load()},[id]);
async function progress(v:number){if(!sb)return;await sb.from("projects").update({progress:v}).eq("id",id);load()}
async function addTask(e:React.FormEvent){e.preventDefault();if(!sb||!task.trim())return;const{error}=await sb.from("project_tasks").insert({project_id:id,title:task.trim()});if(error){setMsg(error.message);return}setTask("");load()}
async function taskProgress(t:any,v:number){if(!sb)return;await sb.from("project_tasks").update({progress:v,status:v>=100?"termine":v>0?"en_cours":"a_faire"}).eq("id",t.id);load()}
async function addLog(e:React.FormEvent){e.preventDefault();if(!sb||!note.trim())return;const{data:{user}}=await sb.auth.getUser();const{error}=await sb.from("project_logs").insert({project_id:id,note:note.trim(),created_by:user?.id||null});if(error){setMsg(error.message);return}setNote("");load()}
async function addExpense(e:React.FormEvent){e.preventDefault();if(!sb||!expense.amount)return;const{data:{user}}=await sb.auth.getUser();const{error}=await sb.from("expenses").insert({project_id:id,category:expense.category,amount:Number(expense.amount),supplier:expense.supplier||null,spent_at:new Date().toISOString().slice(0,10),created_by:user?.id||null,expense_type:"chantier"});if(error){setMsg(error.message);return}setExpense({category:"Matériaux",amount:"",supplier:""});load()}
if(!p)return <Shell title="Chantier"><section className="crmEmpty"><p>{msg||"Chargement du chantier…"}</p></section></Shell>;
const spent=expenses.reduce((s,x)=>s+Number(x.amount||0),0),budget=Number(p.budget||0),contract=Number(p.contract_value||0),progressPct=Number(p.progress||0),remaining=budget-spent,margin=contract-spent,budgetPct=budget>0?(spent/budget)*100:0,expectedPct=progressPct,loss=spent>contract,overBudget=budget>0&&spent>budget,risk=progressPct>0&&budgetPct>progressPct+20,warning=progressPct>0&&budgetPct>progressPct+10,health=loss?"PERTE":overBudget||risk?"RISQUE DE PERTE":warning?"VIGILANCE":"MAÎTRISÉ",healthColor=loss||overBudget||risk?"#dc2626":warning?"#d97706":"#16a34a",done=tasks.filter(x=>Number(x.progress)>=100).length;
return <Shell title="Pilotage chantier"><section className="crmHero"><div><span className="dashBadge">{p.reference||"CHANTIER"}</span><h2>{p.name}</h2><p>{p.clients?.name||"Client"} · {p.project_type||"Projet"} · {p.location||"Localisation à renseigner"}</p><small>Responsable : <strong>{p.manager_name||"À affecter"}</strong></small></div><Link className="btn" href="/chantiers">← Chantiers</Link></section>
<section style={{marginBottom:16,padding:"16px 18px",borderRadius:16,border:`2px solid ${healthColor}`,background:"rgba(255,255,255,.04)",display:"flex",justifyContent:"space-between",gap:16,alignItems:"center",flexWrap:"wrap"}}><div><small>SANTÉ FINANCIÈRE DU CHANTIER</small><h3 style={{margin:"4px 0",color:healthColor}}>● {health}</h3><small>{budgetPct.toFixed(1)}% du budget consommé pour {progressPct}% d’avancement</small></div><div style={{textAlign:"right"}}><small>Écart consommation / avancement</small><strong style={{display:"block",fontSize:22,color:healthColor}}>{(budgetPct-expectedPct).toFixed(1)} pts</strong></div></section><section className="crmStats"><article><span>Avancement</span><strong>{Number(p.progress||0)}%</strong></article><article><span>Contrat</span><strong>{Number(p.contract_value||0).toLocaleString("fr-FR")} FCFA</strong></article><article><span>Budget</span><strong>{Number(p.budget||0).toLocaleString("fr-FR")} FCFA</strong></article><article><span>Dépenses réelles</span><strong>{spent.toLocaleString("fr-FR")} FCFA</strong></article><article><span>Budget restant</span><strong>{remaining.toLocaleString("fr-FR")} FCFA</strong></article><article><span>Marge actuelle</span><strong>{margin.toLocaleString("fr-FR")} FCFA</strong></article></section>
<section className="crmEmpty" style={{textAlign:"left"}}><b>Progression générale</b><input style={{width:"100%",marginTop:12}} type="range" min="0" max="100" step="5" value={p.progress||0} onChange={e=>progress(Number(e.target.value))}/><small>{p.progress||0}% réalisé · Priorité {p.priority||"normale"} · {p.start_date||"Début à définir"} → {p.end_date||"Fin à définir"}</small></section>
<section className="crmEmpty" style={{textAlign:"left"}}><b>Phases & tâches · {done}/{tasks.length} terminées</b><form onSubmit={addTask} style={{display:"flex",gap:8,marginTop:12}}><input required placeholder="Nouvelle phase ou tâche…" value={task} onChange={e=>setTask(e.target.value)}/><button className="miniBtn">Ajouter</button></form>{tasks.map(t=><article className="prospectCard" key={t.id} style={{marginTop:10}}><strong>{t.title}</strong><small>{t.status.replaceAll("_"," ")} · {Number(t.progress)}%</small><input style={{width:"100%"}} type="range" min="0" max="100" step="10" value={t.progress} onChange={e=>taskProgress(t,Number(e.target.value))}/></article>)}</section>
<section className="crmEmpty" style={{textAlign:"left"}}><b>Dépenses & achats chantier</b><form onSubmit={addExpense} className="form2" style={{marginTop:12}}><label>Catégorie<select value={expense.category} onChange={e=>setExpense({...expense,category:e.target.value})}><option>Matériaux</option><option>Main-d’œuvre</option><option>Transport</option><option>Location matériel</option><option>Sous-traitance</option><option>Autre</option></select></label><label>Montant FCFA<input required type="number" min="0" value={expense.amount} onChange={e=>setExpense({...expense,amount:e.target.value})}/></label><label>Fournisseur / bénéficiaire<input value={expense.supplier} onChange={e=>setExpense({...expense,supplier:e.target.value})}/></label><button className="btn goldBtn">Enregistrer la dépense</button></form>{expenses.slice(0,10).map(x=><article className="prospectCard" key={x.id} style={{marginTop:10}}><strong>{x.category} · {Number(x.amount).toLocaleString("fr-FR")} FCFA</strong><small>{x.supplier||"Sans fournisseur"} · {new Date(x.spent_at+"T00:00:00").toLocaleDateString("fr-FR")}</small></article>)}</section>
<section className="crmEmpty" style={{textAlign:"left"}}><b>Journal de chantier</b><form onSubmit={addLog} style={{marginTop:12}}><textarea required rows={3} placeholder="Travaux réalisés, équipes présentes, livraison, difficulté, décision…" value={note} onChange={e=>setNote(e.target.value)}/><button className="btn goldBtn" style={{marginTop:8}}>Ajouter au journal</button></form>{logs.map(l=><article className="prospectCard" key={l.id} style={{marginTop:10}}><strong>{new Date(l.log_date+"T00:00:00").toLocaleDateString("fr-FR")}</strong><small>{l.note}</small></article>)}{msg&&<p className="error">{msg}</p>}</section></Shell>}