"use client";
import{useEffect,useMemo,useState}from"react";
import Shell from"@/components/Shell";
import{supabaseBrowser}from"@/lib/supabase";
export default function Page(){
 const sb=useMemo(()=>supabaseBrowser(),[]),[projects,setProjects]=useState<any[]>([]),[units,setUnits]=useState<any[]>([]),[subs,setSubs]=useState<any[]>([]);
 const[open,setOpen]=useState(false),[msg,setMsg]=useState(""),[f,setF]=useState<any>({name:"",reference:"",location:"",total_area:"",servicing_status:"non_viabilise",description:""});
 async function load(){if(!sb)return;const[a,b,c]=await Promise.all([sb.from("real_estate_projects").select("*").order("created_at",{ascending:false}),sb.from("real_estate_units").select("*"),sb.from("real_estate_subscription_balances").select("*")]);setProjects(a.data||[]);setUnits(b.data||[]);setSubs(c.data||[])}
 useEffect(()=>{load()},[]);
 async function save(e:React.FormEvent){e.preventDefault();if(!sb)return;const{error}=await sb.from("real_estate_projects").insert({...f,total_area:Number(f.total_area||0),reference:f.reference||null});if(error){setMsg(error.message);return}setOpen(false);setF({name:"",reference:"",location:"",total_area:"",servicing_status:"non_viabilise",description:""});load()}
 const available=units.filter(x=>x.status==="disponible").length,sold=units.filter(x=>x.status==="vendu").length,receivable=subs.reduce((s,x)=>s+Number(x.remaining_due||0),0),paid=subs.reduce((s,x)=>s+Number(x.total_paid||0),0);
 return <Shell title="Immobilier"><section className="crmHero"><div><span className="dashBadge">PATRIMOINE & PROMOTION</span><h2>Immobilier & Lotissements</h2><p>Acquisitions, lotissements, lots, souscriptions, échéanciers et recouvrement.</p></div><button className="btn goldBtn" onClick={()=>setOpen(true)}>+ Nouveau projet immobilier</button></section>
 <section className="crmStats"><article><span>Projets</span><strong>{projects.length}</strong></article><article><span>Lots disponibles</span><strong>{available}</strong></article><article><span>Lots vendus</span><strong>{sold}</strong></article><article><span>Encaissements</span><strong>{paid.toLocaleString("fr-FR")} FCFA</strong></article></section>
 <section className="crmStats"><article><span>Créances restantes</span><strong>{receivable.toLocaleString("fr-FR")} FCFA</strong></article><article><span>Souscriptions</span><strong>{subs.length}</strong></article><article><span>Viabilisation</span><strong>{projects.filter(x=>x.servicing_status==="viabilise").length}</strong></article><article><span>Stock total</span><strong>{units.length}</strong></article></section>
 <section className="crmEmpty" style={{textAlign:"left"}}><b>Portefeuille immobilier</b>{projects.length?projects.map(x=>{const pu=units.filter(u=>u.project_id===x.id);return <article className="prospectCard" key={x.id} style={{marginTop:12}}><strong>{x.reference||"PROJET"} · {x.name}</strong><small>{x.location||"Localisation à renseigner"} · {Number(x.total_area||0).toLocaleString("fr-FR")} m²</small><small>{x.servicing_status==="viabilise"?"🟢 Viabilisé":x.servicing_status==="en_viabilisation"?"🟠 En viabilisation":"⚪ Non viabilisé"} · {pu.length} lot(s) · {pu.filter(u=>u.status==="disponible").length} disponible(s)</small><div style={{display:"flex",gap:8,marginTop:8,flexWrap:"wrap"}}><button className="miniBtn">Lots & plan</button><button className="miniBtn">Souscriptions</button><button className="miniBtn">Images / plans</button></div></article>}):<p>Aucun projet immobilier enregistré.</p>}</section>
 {msg&&<p>{msg}</p>}
 {open&&<div className="modal"><form className="modalCard premiumModal" onSubmit={save}><div className="modalTop"><div><span className="dashBadge">NOUVEAU PROJET</span><h2>Créer un projet immobilier</h2></div><button type="button" onClick={()=>setOpen(false)}>×</button></div><label>Nom du projet<input required value={f.name} onChange={e=>setF({...f,name:e.target.value})}/></label><div className="form2"><label>Référence<input value={f.reference} onChange={e=>setF({...f,reference:e.target.value})}/></label><label>Localisation<input value={f.location} onChange={e=>setF({...f,location:e.target.value})}/></label></div><div className="form2"><label>Superficie totale (m²)<input type="number" min="0" value={f.total_area} onChange={e=>setF({...f,total_area:e.target.value})}/></label><label>Viabilisation<select value={f.servicing_status} onChange={e=>setF({...f,servicing_status:e.target.value})}><option value="non_viabilise">Non viabilisé</option><option value="en_viabilisation">En viabilisation</option><option value="viabilise">Viabilisé</option></select></label></div><label>Description<textarea value={f.description} onChange={e=>setF({...f,description:e.target.value})}/></label><button className="btn goldBtn">Enregistrer le projet</button></form></div>}</Shell>
}