"use client";
import {useEffect,useMemo,useState} from "react";
import {supabaseBrowser} from "@/lib/supabase";
type P={id:string;title:string;slug:string;short_summary?:string;description?:string;product_type:string;price:number;cover_path?:string};
export default function Boutique(){
 const sb=useMemo(()=>supabaseBrowser(),[]),[products,setProducts]=useState<P[]>([]),[buy,setBuy]=useState<P|null>(null),[msg,setMsg]=useState(""),[ordered,setOrdered]=useState<{order_number:string}|null>(null),[busy,setBusy]=useState(false),[f,setF]=useState({name:"",email:"",phone:"",whatsapp:""});
 useEffect(()=>{(async()=>{if(!sb)return;const{data}=await sb.rpc("public_academy_products");setProducts((data||[]) as P[])})()},[sb]);
 async function order(e:React.FormEvent){e.preventDefault();if(!sb||!buy||busy||ordered)return;setBusy(true);setMsg("");const{data,error}=await sb.rpc("public_create_training_order",{p_product_id:buy.id,p_buyer_name:f.name,p_buyer_email:f.email,p_buyer_phone:f.phone,p_buyer_whatsapp:f.whatsapp});setBusy(false);if(error){setMsg(error.message);return}const o=data?.[0];setOrdered({order_number:o?.order_number||""});setMsg("Commande "+o?.order_number+" enregistrée. Une seule commande a été créée. Le paiement sécurisé sera disponible à l'étape suivante.");}
 function openBuy(p:P){setBuy(p);setMsg("");setOrdered(null)}
 return <main className="storePage"><header className="storeNav"><a href="/boutique" className="storeBrand"><b>KARMEO</b><span>ACADEMY</span></a><nav><a href="#formations">Formations</a><a href="#expertise">Notre expertise</a></nav><span className="storeSecure">● Boutique sécurisée</span></header>
 <section className="storeHero"><div><span className="academyEyebrow">KARMEO ACADEMY</span><h1>Des compétences qui<br/><em>créent de la valeur.</em></h1><p>Formations et ressources digitales conçues à partir de l'expérience terrain de KARMEO GROUP.</p><a href="#formations" className="academyPrimary">Explorer les formations</a></div><div className="storeHeroK">K<span>A</span></div></section>
 <section className="storeIntro" id="formations"><span className="academyEyebrow">LA BOUTIQUE</span><h2>Choisissez votre prochaine compétence.</h2><p>Accédez à des contenus pratiques, structurés et immédiatement exploitables.</p></section>
 <section className="storeGrid">{products.length?products.map((p,i)=><article className="storeProduct" key={p.id}><div className={"storeCover cover"+(i%3+1)} style={p.cover_path?{backgroundImage:`linear-gradient(#090b1644,#090b16aa),url(${p.cover_path})`}:undefined}><span>{p.product_type==="video"?"MASTERCLASS":p.product_type==="pdf"?"GUIDE DIGITAL":"PACK EXPERT"}</span><div>K</div><small>KARMEO ACADEMY</small></div><div className="storeProductBody"><span className="storeType">{p.product_type.toUpperCase()}</span><h3>{p.title}</h3><p>{p.short_summary||p.description||"Une formation KARMEO conçue pour transformer l'expertise en résultats concrets."}</p><div className="storeBuy"><strong>{Number(p.price).toLocaleString("fr-FR")} <small>FCFA</small></strong><button onClick={()=>openBuy(p)}>Acheter</button></div></div></article>):<div className="storeEmpty"><b>Les premières formations arrivent bientôt.</b><p>La boutique KARMEO Academy est en cours de préparation.</p></div>}</section>
 <section className="storeExpertise" id="expertise"><span>KARMEO ACADEMY</span><h2>L'expertise terrain, disponible partout.</h2><p>Une boutique indépendante de l'ERP KARMEO GROUP. Les visiteurs accèdent uniquement aux produits Academy et au parcours d'achat.</p></section>
 <footer className="storeFooter"><b>KARMEO ACADEMY</b><span>© KARMEO GROUP</span></footer>
 {buy&&<div className="modal"><form className="modalCard premiumModal storeCheckout" onSubmit={order}><div className="modalTop"><div><span className="dashBadge">COMMANDE</span><h2>{buy.title}</h2></div><button type="button" onClick={()=>setBuy(null)}>×</button></div><div className="checkoutPrice">{Number(buy.price).toLocaleString("fr-FR")} FCFA</div><label>Nom complet<input required disabled={!!ordered} value={f.name} onChange={e=>setF({...f,name:e.target.value})}/></label><label>E-mail<input type="email" disabled={!!ordered} value={f.email} onChange={e=>setF({...f,email:e.target.value})}/></label><div className="form2"><label>Téléphone<input disabled={!!ordered} value={f.phone} onChange={e=>setF({...f,phone:e.target.value})}/></label><label>WhatsApp<input disabled={!!ordered} value={f.whatsapp} onChange={e=>setF({...f,whatsapp:e.target.value})}/></label></div>{msg&&<p className="notice">{msg}</p>}<button className="academyPrimary full" type="submit" disabled={busy||!!ordered}>{busy?"Enregistrement…":ordered?"Commande enregistrée ✓":"Continuer vers le paiement →"}</button></form></div>}
 </main>
}